% =====================================================================
% correctness.pl — contract-based verification rules.
%
% These rules operate on Hoare triples (precondition/2, postcondition/2)
% and loop invariants (invariant/2) generated by the formalize module.
% They extend the governance violation/2 framework with semantic checks.
% =====================================================================

% P3 (correctness): a read-intent routine with mutation side effect
% contradicts its own postcondition if it claims to only return data.
violation(Routine, 'postcondition-contradiction') :-
    postcondition(Routine, Post),
    intent(Routine, read),
    side_effect(Routine, mutation).

% P3 (correctness): a routine with a precondition that its caller
% does not also assert — potential precondition violation.
violation(Caller, 'precondition-not-checked') :-
    calls(Caller, Callee),
    precondition(Callee, _),
    \+ precondition(Caller, _).

% P1 (membrane): loop with crypto but invariant claims no crypto effect
% — the invariant is wrong or the code is dangerous.
violation(Scope, 'invariant-crypto-contradiction') :-
    invariant(Scope, _),
    crypto_in_loop(Scope).

% P2 (speed): loop with serial awaits but invariant claims bounded time
violation(Scope, 'invariant-await-contradiction') :-
    invariant(Scope, _),
    awaits_in_loop(Scope).
